### PR TITLE
Fix regression on bigendian

### LINKED ISSUE #57: Broken on bigendian (regression)
Test suite segfault on bigendian (ex: s390x)

Ex see https://koji.fedoraproject.org/koji/taskinfo?taskID=101715276

Related to f0a18720cb19d4c34ed7b52abc6e1dc3c8722999 (I will add comment there)

### PR DESCRIPTION
**Pull request by remicollet**
- rewrite IP2Location_read32_row
- more robust detection of endianness

Fedora scratch build using this fix:
https://koji.fedoraproject.org/koji/taskinfo?taskID=101823859

Fix #57

### CODE REVIEW

File: libIP2Location/IP2Location.c [hunk 1]
```diff
@@ -1432,58 +1423,59 @@ char *IP2Location_read_string(FILE *handle, uint32_t position)
...
 float IP2Location_readFloat(FILE *handle, uint32_t position)
 {
+	int endian = 1;
 	float ret = 0.0;
 	uint8_t *cache_shm = memory_pointer;
 	size_t temp;
 
-#if defined(_SUN_) || defined(__powerpc__) || defined(__ppc__) || defined(__ppc64__) || defined(__powerpc64__)
-	char *p = (char *) &ret;
+	if (*(char*)&endian==0) {    /* BIG ENDIAN */
```
Comment (remicollet) [inline libIP2Location/IP2Location.c:1431]: Only test is changed, other lines are only indentation.
(such runtime test will be optimized by compiler as always true/false)

**Comment by remicollet** [comment]
Perhaps `WORDS_BIGENDIAN` (from configure) can be used, but I don't know if `AC_C_BIGENDIAN` is reliable.

For ex, PHP use its own function, see https://github.com/php/php-src/blob/php-8.2.6/build/php.m4#L1691

**Review by pbiering — APPROVED** [review]
Looks good

**Comment by sharkcz** [comment]
Or the gcc (and other compilers) define `__BYTE_ORDER__` and comparison to `____ORDER_BIG_ENDIAN__` can be used.

The `AC_C_BIGENDIAN`  check works well too.

**Comment by pbiering** [comment]
@remicollet : would you adjust your PR according to @sharkcz comments? Then I will wait creating RPMs.

**Comment by remicollet** [comment]
@sharkcz @pbiering running test build using `WORDS_BIGENDIAN`

**Comment by remicollet** [comment]
Scratch build seems OK https://koji.fedoraproject.org/koji/taskinfo?taskID=101826163

PR updated

**Review by pbiering — APPROVED** [review]
Looks even better as the former one!

**Comment by pbiering** [comment]
8.6.0 with this patch submitted now for update
- https://koji.fedoraproject.org/koji/packageinfo?packageID=32132
- https://bugzilla.redhat.com/show_bug.cgi?id=2211835
- https://bodhi.fedoraproject.org/updates/?packages=IP2Location
